name: Deploy Web Staging

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ice-pulse-web:staging-latest.RELEASE
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy notification
      run: |
        echo "✅ Web Staging deployed successfully"
        echo "🔄 Watchtower will auto-update in ~5 minutes"